### ISSUE TITLE
Bitbucket template fails to Deploy due to missing Elasticsearch chart

### ISSUE THREAD

**Issue by chrisgelhaus** [Praqma/ask#2]
I added the Praqma chart catalog to my Rancher installation.
I go to Apps-->Launch and select the Praqma Bitbucket chart
I supply a few values and then click Launch. The app fails to install with the following message:

Wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: elasticsearch : exit status 1

**Comment by hoeghh** [comment]
Hi @chrisgelhaus 

Sorry for the late response. We only played with the Rancher catalog. We havent finished it yet. 
And, the docker images are stored in a private repo on Docker hub. You need to build them your self and push to a repo you own, and then refer to those instead.

I hope it makes sense.

**Comment by chrisgelhaus** [comment]
Thank you for the response. It sort of makes sense. I'm building the image for bitbucket myself using your Dockerfile, and I am specifying my image name in the values.yaml file; However, when I try to use your chart to deploy it fails due to the dependency on Elasticsearch. 
I've tried setting both conditions elasticsearch.enabled and global.elasticsearch.enabled to false, but it hasn't helped.
I was trying to avoid cloning your bitbucket chart, but it looks like I may have to.

I hope this makes sense!

**Comment by hoeghh** [comment]
Do you get "Preventing ElasticSearch from starting ..." in the logs of the container when starting it?

**Comment by TNissen377** [comment]
+1

**Comment by chrisgelhaus** [comment]
Update,
This was caused by my own lack of knowledge. I was still learning helm charts and I did not update the dependencies before deploying the chart. Once I updated the dependencies, it worked. 

Closing issue.
