### ISSUE TITLE
Error response from daemon: pull access denied for praqma/jira, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by jc1518** [Praqma/ask#4]
After installed jira helm chart, the Pod status is always as 'Waiting: ImagePullBackOff'. Looks to me the praqma/jira image either does not exist or is private.

Here is my test:

`$ docker login
Authenticating with existing credentials...
Login Succeeded

$ docker pull praqma/jira
Using default tag: latest
Error response from daemon: pull access denied for praqma/jira, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by michaelvl** [comment]
The above commits refer to issue #5 not this issue

**Comment by hoeghh** [comment]
Hi @jc1518 
Sorry for the late response.
The docker repos are private. So you need to build the images your self, and push to your own repo.
