### ISSUE TITLE
Jira incorrect readiness probe

### ISSUE THREAD

**Issue by michaelvl** [Praqma/ask#8]
The 'readinessProbe.httpGet' gets passed elements that belong at the 'readiness' object level.

File: https://github.com/Praqma/ask/blob/master/jira/templates/statefulset.yaml

See also https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#probe-v1-core

**Comment by michaelvl** [comment]
helm2 template jira | kubectl apply -f -

rror: error validating "STDIN": error validating data: [ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "failureThreshold" in io.k8s.api.core.v1.HTTPGetAction, ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "initialDelaySeconds" in io.k8s.api.core.v1.HTTPGetAction, ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "periodSeconds" in io.k8s.api.core.v1.HTTPGetAction, ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "successThreshold" in io.k8s.api.core.v1.HTTPGetAction, ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "timeoutSeconds" in io.k8s.api.core.v1.HTTPGetAction]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by sami-alajrami** [comment]
fixed in https://github.com/Praqma/ask/pull/9
